### PR TITLE
Add Footer and Footer Card

### PR DESCRIPTION
**Pull request by BhaveshDiwale**
Added Footer component with Footer card.

### CODE REVIEW

**Comment by BhaveshDiwale** [comment]
Hi! All the issues of Footer component are now resolved. Please merge it to your code. Thanks.

**Comment by atharv-av** [comment]
Before we merge it to the main code, @BhaveshDiwale can you try making it responsive?

**Comment by BhaveshDiwale** [comment]
> Before we merge it to the main code, @BhaveshDiwale can you try making it responsive? And do drop a comment on the footer issue.

Ok sure!

**Comment by BhaveshDiwale** [comment]
Hi! Footer is now fully responsive.
Note that the Why Join Us Section is conflicting because of its hover effect addition. 
The Footer is now ready to be merged. Thanks.

**Comment by BhaveshDiwale** [comment]
> Great job @BhaveshDiwale . Your PR is merged.

Thanks @atharv-av .

**Pull request merged**
