### PR TITLE
[FEAT] : Added Join US Card Hover Effect Successfully.

### LINKED ISSUE #16: Join us card hover effect
Add a beautiful hover effect to the join us cards.

### PR DESCRIPTION
**Pull request by Raj-Mandal-20**
Fixes #16

### CODE REVIEW

**Comment by atharv-av** [comment]
Hello @Raj-Mandal-20 , thanks for your contribution, but I'd like to suggest a few things here.
- Add transition duration to the hover effect.
- Design the border shadow in a better way or use another hover effect.

Consider this and create another pull request.

**Comment by Raj-Mandal-20** [comment]
Hello @atharv-av 

>  * <h5> I have added  transition duration to the hover effect.  </h5> 
> *  <h5>  And also Design the border shadow in a better way. </h5>

**Comment by atharv-av** [comment]
Thanks for considering the suggestion @Raj-Mandal-20 . Your PR is now merged.

**Comment by Raj-Mandal-20** [comment]
Thank You @atharv-av

**Pull request merged**
