### PR TITLE
[FEAT]:  Create Navbar

### LINKED ISSUE #1: Create navbar.
Refer to the Figma design provided in the Readme file and create the navbar component (preferably using TailwindCSS).

### PR DESCRIPTION
**Pull request by Raj-Mandal-20**
Fixes #1 

> * <h4> Made Responsive Design For Both Mobile, Tablet and Desktop Devices. </h4>

### CODE REVIEW

**Comment by Raj-Mandal-20** [comment]
@atharv-av could you please verify this.

**Comment by atharv-av** [comment]
Hello, I just reviewed it and it's awesome. I just have one suggestion that the items in the navbar can have a bit more gap and the list items can have a bit more margin and padding. Can you please make the suggested changes and create another PR?

**Comment by atharv-av** [comment]
Hello, I have verified and merged your pull request.

**Comment by Raj-Mandal-20** [comment]
Hii, @atharv-av my contribution on this PR is excluded from hacktoberfest could you give me some suggesstions that how do i fix it.

**Pull request merged**
